<a href="https://colab.research.google.com/github/wasi-coder/computer-vision-using-tensorflow/blob/main/tensorflow_practice_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow


In [ ]:
import tensorflow as tf
print (tf.__version__)

2.18.0


In [ ]:
tensor_zero_d = tf.constant(4)
print (tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,2,1,-3.2])
print (tensor_one_d)

tf.Tensor([ 2.   2.   1.  -3.2], shape=(4,), dtype=float32)


In [ ]:
tensor_two_d_ =tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [2,6,-9.1]
])
print(tensor_two_d_)

tf.Tensor(
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 2.   6.  -9.1]], shape=(4, 3), dtype=float32)


In [ ]:
import numpy as np
np_array  = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [ ]:
converted_tensor =tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print (1*eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)
