<a href="https://colab.research.google.com/github/wasi-coder/computer-vision-using-tensorflow/blob/main/tensorflow_practice_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow


In [7]:
import tensorflow as tf
print (tf.__version__)

2.18.0


In [ ]:
tensor_zero_d = tf.constant(4)
print (tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,2,1,-3.2])
print (tensor_one_d)

tf.Tensor([ 2.   2.   1.  -3.2], shape=(4,), dtype=float32)


In [ ]:
tensor_two_d_ =tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [2,6,-9.1]
])
print(tensor_two_d_)

tf.Tensor(
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 2.   6.  -9.1]], shape=(4, 3), dtype=float32)


In [7]:
import numpy as np
np_array  = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [ ]:
converted_tensor =tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [10]:
eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print (1*eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [15]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=2,
    batch_shape=[3,2],
    dtype=tf.dtypes.int32,
    name=None

    )
print (eye_tensor)

tf.Tensor(
[[[[1 0]
   [0 1]
   [0 0]]

  [[1 0]
   [0 1]
   [0 0]]]


 [[[1 0]
   [0 1]
   [0 0]]

  [[1 0]
   [0 1]
   [0 0]]]


 [[[1 0]
   [0 1]
   [0 0]]

  [[1 0]
   [0 1]
   [0 0]]]], shape=(3, 2, 3, 2), dtype=int32)


In [17]:
fill_tensor = tf.fill(
    [2,3],4,name=None
)
print(fill_tensor
      )

tf.Tensor(
[[4 4 4]
 [4 4 4]], shape=(2, 3), dtype=int32)


In [21]:
ones_tensor = tf.ones(
    [2,3],
    dtype=tf.dtypes.int64,
    name="wasi"
)
print(ones_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int64)


In [30]:
random_tensor = tf.random.normal(
    [3,3],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float16,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 98.4  99.7  99.8]
 [ 99.6  99.6 101.3]
 [102.1  98.8 100.2]], shape=(3, 3), dtype=float16)


In [5]:
random_uniform_tensor = tf.random.uniform(
    [3,3],
    minval=0,
    maxval=5,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_uniform_tensor
)

tf.Tensor(
[[3 4 4]
 [0 1 3]
 [2 0 2]], shape=(3, 3), dtype=int32)


In [17]:
t = tf.constant([1,2,378,4,5,34,345,453,6456,8567,789,67])
print(t[1::2])

tf.Tensor([   2    4   34  453 8567   67], shape=(6,), dtype=int32)


In [13]:
tf.range(2,5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [21]:
print(random_uniform_tensor[:,:])

tf.Tensor(
[[3 4 4]
 [0 1 3]
 [2 0 2]], shape=(3, 3), dtype=int32)


In [23]:
a = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=500,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(a)

tf.Tensor(
[[178  83 374 116 130]
 [271  61 148 468 179]
 [460 123 117 259 239]
 [467 248 341 105 256]
 [218 355 132 376 242]], shape=(5, 5), dtype=int32)


In [24]:
print(a[...,2])

tf.Tensor([374 148 117 341 132], shape=(5,), dtype=int32)


In [27]:
ass = tf.random.uniform(
    [5,5,3],
    minval=0,
    maxval=500,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(ass)

tf.Tensor(
[[[112  49 256]
  [ 59 447 397]
  [394 480 188]
  [130 364 310]
  [ 33  44 483]]

 [[224 124 233]
  [ 18 319 133]
  [321 322 336]
  [ 83 457  42]
  [170 303 340]]

 [[205  51 351]
  [199 313 166]
  [343 334 264]
  [386   9 397]
  [  0 370 163]]

 [[397 257  56]
  [208 480 310]
  [439 362 141]
  [422 134   8]
  [314  78  40]]

 [[128  25 210]
  [170 316 102]
  [  0 473  59]
  [403 289 493]
  [275 494 311]]], shape=(5, 5, 3), dtype=int32)


In [29]:
complex_num = tf.constant([2+3j])
print(tf.abs(complex_num))

tf.Tensor([3.60555128], shape=(1,), dtype=float64)
